[package]
name = "sunspec-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
quick-xml = "0.31"
tracing = { workspace = true }
thiserror = { workspace = true }

types = { path = "../types" }
